[project]
authors = ["Cristian Adamo", "Manuel Saelices"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "mojo-libc"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.13"

[dependencies]
max = ">=25.1.0.dev2025011705"
